### ISSUE TITLE
Binaries? Or at lease build instructions??

### ISSUE THREAD

**Issue by adolfintel** [bisqwit/adlmidi#1]
Seriously, there are no build instructions and no binaries, what the fuck am I supposed to do? Guess how to build it?

**Comment by bisqwit** [comment]
I guess you are not familiar with building software from source?
In general, typing ‘make’ does stuff. This is how stuff works with at least 99,9% of open source projects. Basically with almost anything you download from the Internet. Sometimes you need to type ‘./configure’ first, but this step is not required for ADLMIDI.
Funny that you didn’t think of it.

Well, unless you are running Windows. If you have chosen to encumber yourself with a Windows-based platform, then… my condolences.

**Comment by adolfintel** [comment]
I do it occasionally on linux, but here I'm trying to use Cygwin on windows, which is a pain in the ass. You have a screenshot of the program running on Windows 7 on your site, how did you build it?

**Comment by bisqwit** [comment]
Maybe this is your first open source project you come across. In that case, being more polite and not starting off with language like “fuck” would be a good start.

For Cygwin… you type ‘make‘.

**Comment by adolfintel** [comment]
It doesn't work, that was the first thing I tried.
I'm trying to install the deps it needs one by one, right now I'm at SDL, which package is required?

My apologies for yelling at you, I've been trying to build it for over an hour.

**Comment by adolfintel** [comment]
![image](https://user-images.githubusercontent.com/16307689/39206934-fe5cf074-47fe-11e8-9da1-5c953d99c886.png)

**Comment by bisqwit** [comment]
As a general notion though, Windows support is provided as least-effort without any guarantee of being maintained. I don’t run Windows except very very randomly and occasionally, and it is even rarer that I try to build software on Windows. So pardon me that I have not expended effort in writing extensive instructions for Windows-encumbered people.

If SDL is not available in Cygwin package manager, you will have to build it from source. Unfortunately I don’t have access to a running Windows system at the moment, so I am unable to provide instructions how to do that, at least not instructions that would be better than those available within SDL website or its source code package.

And then, for ADLMIDI… You may have to edit Makefile and switch out the compiler definition near the beginning of the file. Zero or more of the provided examples at the top of the file might work. I say zero, because things seem to have changed every single time I try it in Windows. Things aren’t easy in Windows-land.

**Comment by adolfintel** [comment]
Does it cross-compile from linux or does it require some modifications?

**Comment by bisqwit** [comment]
-Ofast has been supported by GCC since version 4.6. The version that prints those errors cannot be GCC 6.4.0.

**Comment by adolfintel** [comment]
Ah, it looks like gcc was installed but not in the path. Now it almost builds. It's missing SDL.h now.

**Comment by bisqwit** [comment]
You can try cross-compilation for Windows from Linux. Like I said things are provided at least-effort. Windows support is not exactly a priority for me. I am open for push requests that improve things in a well designed manner though.

**Comment by adolfintel** [comment]
I understand your point of view, but you have an awesome project here, and Windows has 95% of the market share...

**Comment by bisqwit** [comment]
This is not a commercial project, so I could not care less about market.

Windows is a hostile environment for developers, and that keeps me out from it.

**Comment by bisqwit** [comment]
Oh by the way, SDL is not required for the Windows version. The code that depends on SDL is automatically disabled if either `__WIN32__` or `__CYGWIN__` is defined.

**Comment by bisqwit** [comment]
Cross-compilation from Linux seems to mostly work if you switch the CC defines and disable the SDL defines in Makefile. There seems to be at least one standard function (setbuffer) that is missing from at least my version of mingw, so I digress.

**Comment by bisqwit** [comment]
Shouldn’t be blocking. If it blocks, try fixing it. I don’t have a Windows computer here at hand to test it out and to debug it.

**Comment by bisqwit** [comment]
Try a different buffer size perhaps.  Or try the older version that I used when recording this video: https://www.youtube.com/watch?v=7IeO7CYFd9E (probably commit 8330d5cbf35b7745a10d2bb89e75ea000a33387d)

**Comment by adolfintel** [comment]
I already tried changing the buffer size. I think it has something to do with how you draw to the screen. I'll see if I can do something

**Comment by adolfintel** [comment]
setting const double OurHeadRoomLength = 5; "fixes" the sound stuttering. The screen is all messed up though, even on xterm.

**Comment by adolfintel** [comment]
Looks like this in all terminals I have installed 

![image](https://user-images.githubusercontent.com/16307689/39209707-ce3f4704-4806-11e8-8279-3e1d57ac0999.png)

**Comment by bisqwit** [comment]
Yeah I am aware the terminal size recognition is wonky and does not quite work properly. (And even if it recognizes it, it does not perfectly honor it. You are better off using a large terminal with small font :-))
This problem is not specific to Windows, it affects Linux too.

**Comment by adolfintel** [comment]
Just for curiosity, I see you have included a way to output to ffmpeg. Does that work? I have an (unpublished) project where I used ffmpeg to do stuff in real time and it was a pain in the ass

**Comment by bisqwit** [comment]
It worked when I needed it. That’s what I have used for the videos on https://www.youtube.com/channel/UCHFXRDwqIlcwcRSSSUmJJ5g/videos?disable_polymer=1 . Whether it still works I am unable to say for sure.

**Comment by adolfintel** [comment]
I thought the UI lag and the sound stuttering were related but I was wrong, How odd.

Either way, it's good to have a decent Midi OPL player.

**Comment by adolfintel** [comment]
In case some other poor soul wants to use this on Windows, I'll leave the binaries here.
[binaries.zip](https://github.com/bisqwit/adlmidi/files/1944361/binaries.zip)

Thanks again for your help. I can send you a donation if you want ;)
