### ISSUE TITLE
`-w` should disable looping

### ISSUE THREAD

**Issue by fenugrec** [bisqwit/adlmidi#13]
It seems using `-w` to produce a .wav file will continue forever. I noticed when the file was at 400MB (36 minutes) and still growing. I suggest disable looping in this mode.

**Comment by bisqwit** [comment]
It is a good practice to use `-w` and `-nl` in conjunction. There is no option to _enable_ looping, so should you want to create a WAV file that loops through a MIDI file several times, the suggested change would make it impossible.

**Comment by fenugrec** [comment]
I find it strange to have default behaviour to loop indefinitely, eating up all available disk space, but OK if it's on purpose.
