### ISSUE TITLE
stderr is set up using C standard library function.

### ISSUE THREAD

**Issue by MechanicalPen** [bisqwit/adlmidi#2]
On this line;
https://github.com/bisqwit/adlmidi/blob/master/midiplay.cc#L361

``setbuffer(stderr, stderr_buffer, sizeof(stderr_buffer));`` (the c form) is used rather than, ``setvbuf(stderr, stderr_buffer, _IONBF, sizeof(stderr_buffer));`` (the c++ form).

I only noticed this because I don't have the C language build tools installed, so compilation failed.

**Comment by bisqwit** [comment]
Good point! I did not realize this function was not brought into C++. The std:: prefix is missing there because I thought it was a library defect, but I never bothered to verify.
Fixed in commit 2f3a6263b79b832efac1feda07cee07820dfc309.
